namespace Xsd2CSharp.Core.Generation;

/// <summary>
/// Source text for the small runtime support file emitted alongside every generated schema
/// (once per output - the CLI writes it as its own .cs file, the source generator adds it as
/// an extra generated source). It has no dependency on anything preview-only; only the
/// generated model classes/unions require <c>LangVersion=preview</c>.
/// </summary>
public static class RuntimeSource
{
    public const string BaseName = "Xsd2CSharpRuntime";
    public const string FileName = BaseName + ".g.cs";
    public const string ClrNamespace = "Xsd2CSharp.Runtime";

    public const string Text = """
        // <auto-generated>
        //     This file was generated by the Xsd2CSharp tool from an XSD schema.
        //     Changes made to this file may be lost when it is regenerated, and may
        //     result in incorrect behavior. Do not edit this file directly.
        // </auto-generated>
        namespace Xsd2CSharp.Runtime
        {
            using System;
            using System.Collections.Generic;
            using System.Globalization;
            using System.Numerics;
            using System.Xml;

            /// <summary>
            /// Lexical-space parse/format helpers used by generated ReadXml/WriteXml implementations.
            /// Deliberately hand-rolled instead of relying on System.Xml.Serialization.XmlSerializer,
            /// which cannot express NMTOKEN-derived enumerations or C# union (choice) types declaratively.
            /// </summary>
            internal static class XsdConvert
            {
                public static string Format(bool value) => XmlConvert.ToString(value);
                public static bool ParseBoolean(string value) => XmlConvert.ToBoolean(value.Trim());

                public static string Format(decimal value) => XmlConvert.ToString(value);
                public static decimal ParseDecimal(string value) => XmlConvert.ToDecimal(value.Trim());

                public static string Format(float value) => XmlConvert.ToString(value);
                public static float ParseSingle(string value) => XmlConvert.ToSingle(value.Trim());

                public static string Format(double value) => XmlConvert.ToString(value);
                public static double ParseDouble(string value) => XmlConvert.ToDouble(value.Trim());

                public static string Format(sbyte value) => XmlConvert.ToString(value);
                public static sbyte ParseSByte(string value) => XmlConvert.ToSByte(value.Trim());

                public static string Format(byte value) => XmlConvert.ToString(value);
                public static byte ParseByte(string value) => XmlConvert.ToByte(value.Trim());

                public static string Format(short value) => XmlConvert.ToString(value);
                public static short ParseInt16(string value) => XmlConvert.ToInt16(value.Trim());

                public static string Format(ushort value) => XmlConvert.ToString(value);
                public static ushort ParseUInt16(string value) => XmlConvert.ToUInt16(value.Trim());

                public static string Format(int value) => XmlConvert.ToString(value);
                public static int ParseInt32(string value) => XmlConvert.ToInt32(value.Trim());

                public static string Format(uint value) => XmlConvert.ToString(value);
                public static uint ParseUInt32(string value) => XmlConvert.ToUInt32(value.Trim());

                public static string Format(long value) => XmlConvert.ToString(value);
                public static long ParseInt64(string value) => XmlConvert.ToInt64(value.Trim());

                public static string Format(ulong value) => XmlConvert.ToString(value);
                public static ulong ParseUInt64(string value) => XmlConvert.ToUInt64(value.Trim());

                public static string Format(BigInteger value) => value.ToString(CultureInfo.InvariantCulture);
                public static BigInteger ParseBigInteger(string value) => BigInteger.Parse(value.Trim(), CultureInfo.InvariantCulture);

                public static string Format(DateTimeOffset value) => XmlConvert.ToString(value);
                public static DateTimeOffset ParseDateTimeOffset(string value)
                {
                    var s = value.Trim();
                    // xsd:dateTime permits the timezone to be entirely absent, meaning "unspecified" -
                    // but XmlConvert.ToDateTimeOffset silently assumes the *ambient machine's* local
                    // timezone in that case, making the parsed value depend on where/when the code
                    // happens to run. Default to UTC instead (deterministic) by appending "Z" before
                    // handing off to XmlConvert, but only when no zone designator is already present -
                    // an explicit Z/offset in the source is left completely untouched.
                    var hasZone = s.Length > 0 && s[s.Length - 1] == 'Z';
                    if (!hasZone)
                    {
                        // A "+hh:mm"/"-hh:mm" suffix can only start after the fixed-length date
                        // portion ("yyyy-MM-dd", 10 chars) - anything at or before that index is one
                        // of the date's own "-" separators, not a timezone sign.
                        var sign = Math.Max(s.LastIndexOf('+'), s.LastIndexOf('-'));
                        hasZone = sign > 10;
                    }
                    return XmlConvert.ToDateTimeOffset(hasZone ? s : s + "Z");
                }

                public static string Format(DateOnly value) => value.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
                public static DateOnly ParseDateOnly(string value)
                {
                    var s = value.Trim();
                    // Ignore an optional trailing timezone offset (xsd:date allows one; DateOnly has no timezone concept).
                    var end = 10;
                    return DateOnly.ParseExact(s.Substring(0, Math.Min(end, s.Length)), "yyyy-MM-dd", CultureInfo.InvariantCulture);
                }

                public static string Format(TimeOnly value) => value.ToString("HH:mm:ss.FFFFFFF", CultureInfo.InvariantCulture);
                public static TimeOnly ParseTimeOnly(string value)
                {
                    var s = value.Trim();
                    // Strip an optional trailing timezone offset (Z or +hh:mm/-hh:mm).
                    var end = s.Length;
                    if (end > 0 && s[end - 1] == 'Z') end--;
                    else
                    {
                        var plus = s.LastIndexOf('+');
                        var minus = s.LastIndexOf('-');
                        var sign = Math.Max(plus, minus);
                        if (sign > 8) end = sign; // avoid matching '-' inside e.g. "12:00:00"
                    }
                    return TimeOnly.Parse(s.Substring(0, end), CultureInfo.InvariantCulture);
                }

                public static string Format(Uri value) => value.OriginalString;
                public static Uri ParseUri(string value) => new(value.Trim(), UriKind.RelativeOrAbsolute);

                public static string FormatHexBinary(byte[] value) => Convert.ToHexString(value);
                public static byte[] ParseHexBinary(string value) => Convert.FromHexString(value.Trim());

                public static string FormatBase64Binary(byte[] value) => Convert.ToBase64String(value);
                public static byte[] ParseBase64Binary(string value) => Convert.FromBase64String(value.Trim());

                /// <summary>Splits an xsd:list lexical value (e.g. NMTOKENS) on XML whitespace.</summary>
                public static string[] SplitList(string value) =>
                    value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);

                /// <summary>Joins formatted item values into an xsd:list lexical value.</summary>
                public static string JoinList(IEnumerable<string> items) => string.Join(" ", items);

                /// <summary>
                /// Applies an XSD default="..."/fixed="..." value-constraint: per the XSD spec, when an
                /// element or attribute is *present but empty* (e.g. "&lt;Foo/&gt;"), a schema-aware
                /// processor treats its value as the declared default/fixed value rather than as literal
                /// empty text - distinct from the element being omitted entirely. Real schemas rely on
                /// this heavily for booleans/enums that are conventionally left empty when they'd equal
                /// the default anyway.
                /// </summary>
                public static string DefaultIfEmpty(string value, string defaultValue) => value.Length == 0 ? defaultValue : value;
            }
        }
        """;
}
