using System.Collections.Generic;
using System.Linq;
using System.Text;
using Xsd2CSharp.Core.Model;
using Xsd2CSharp.Core.Naming;

namespace Xsd2CSharp.Core.Generation;

/// <summary>
/// One generated source file: a suggested base file name (no extension - callers append their own,
/// e.g. ".cs" for files written to disk by the CLI or ".g.cs" for a source generator's AddSource),
/// the C# namespace its type(s) live in (callers place multi-namespace output into matching
/// subfolders), and its full C# content.
/// </summary>
public sealed record GeneratedFile(string BaseName, string ClrNamespace, string Content);

/// <summary>
/// Emits C# source for a <see cref="SchemaModel"/>: enums (+ Parse/Format companions), C# 15
/// union declarations for xsd:choice/xsd:union (+ TryRead/Write or Parse/Format companions),
/// and classes implementing <c>IXmlSerializable</c> by hand (not via declarative
/// <c>System.Xml.Serialization</c> attributes - see the type-level doc comments in
/// <see cref="Xsd.SchemaModelBuilder"/> for why).
/// </summary>
public static class SchemaCodeGenerator
{
    private const string XsiNs = "http://www.w3.org/2001/XMLSchema-instance";

    /// <summary>
    /// Generates one file per top-level type (each class, enum, and union - a union's file also
    /// holds its case wrapper records and Xml companion class, since they only ever make sense
    /// together) plus one "Documents" file per namespace for that namespace's root-element
    /// Load/Save helpers, rather than a single giant file - much easier to navigate, diff, and (for
    /// very large schemas) compile. A type is emitted into its own XSD targetNamespace's C#
    /// namespace (see SchemaModelBuilder) - every file gets a `using` for every namespace the schema
    /// uses, so a type in one namespace can always reference one from another without per-file
    /// dependency analysis.
    /// </summary>
    public static IReadOnlyList<GeneratedFile> Generate(SchemaModel model)
    {
        Refs refs = new(model);
        List<string> allNamespaces = [.. model.AllClrNamespaces];
        List<GeneratedFile> files = [];

        foreach (EnumTypeModel e in model.Enums)
            files.Add(EmitFile(e.ClrNamespace, allNamespaces, e.ClrName, w => EmitEnum(w, e, refs)));

        foreach (UnionTypeModel u in model.Unions)
            files.Add(EmitFile(u.ClrNamespace, allNamespaces, u.ClrName, w => EmitUnion(w, u, refs)));

        foreach (ClassTypeModel c in model.Classes)
            files.Add(EmitFile(c.ClrNamespace, allNamespaces, c.ClrName, w => EmitClass(w, c, refs)));

        foreach (IGrouping<string, RootElementModel> rootGroup in model.RootElements.GroupBy(r => r.ClrNamespace))
            files.Add(EmitFile(rootGroup.Key, allNamespaces, "Documents", w => EmitRootDocuments(w, rootGroup, refs)));

        return files;
    }

    private static GeneratedFile EmitFile(string clrNamespace, List<string> allNamespaces, string baseName, Action<CodeWriter> body)
    {
        CodeWriter w = new();
        w.Line("// <auto-generated>");
        w.Line("//     This file was generated by the Xsd2CSharp tool from an XSD schema.");
        w.Line("//     Changes made to this file may be lost when it is regenerated, and may");
        w.Line("//     result in incorrect behavior. Do not edit this file directly.");
        w.Line("// </auto-generated>");
        w.Line();
        w.Line("using System;");
        w.Line("using System.Collections.Generic;");
        w.Line("using System.Xml;");
        w.Line("using Xsd2CSharp.Runtime;");
        foreach (string ns in allNamespaces.Where(ns => ns != clrNamespace))
            w.Line($"using {ns};");
        w.Line();

        using (w.Block($"namespace {clrNamespace}"))
            body(w);

        return new GeneratedFile(SafeFileName(baseName), clrNamespace, w.ToString());
    }

    /// <summary>
    /// Deeply-nested context names (e.g. a union built from a choice three levels down inside
    /// another union's row) can produce type names long enough to blow past Windows' ~260-char
    /// MAX_PATH once each type gets its own file. The C# identifier itself is unaffected - only
    /// the file name is shortened, with a deterministic hash suffix so it stays unique.
    /// </summary>
    private static string SafeFileName(string baseName)
    {
        const int maxLen = 100;
        if (baseName.Length <= maxLen)
            return baseName;

        string hash = Fnv1aHash(baseName).ToString("x8");
        int keep = maxLen - hash.Length - 1;
        return $"{baseName.Substring(0, keep)}_{hash}";
    }

    // FNV-1a: simple, deterministic, stable across runs/processes (unlike string.GetHashCode()).
    private static uint Fnv1aHash(string value)
    {
        uint hash = 2166136261u;
        foreach (char ch in value)
        {
            hash ^= ch;
            hash *= 16777619u;
        }
        return hash;
    }

    private static void EmitEnum(CodeWriter w, EnumTypeModel e, Refs refs)
    {
        EmitXmlRootAttributeIfAny(w, e.ClrName, refs);
        using (w.Block($"public enum {e.ClrName}"))
        {
            foreach (EnumMemberModel m in e.Members)
                w.Line($"{m.ClrName},");
        }
        w.Line();

        using (w.Block($"internal static class {e.ClrName}Xml"))
        {
            // NMTOKEN/token (unlike plain string/normalizedString) have XSD's "collapse" whitespace
            // facet: leading/trailing whitespace is stripped (and internal runs collapsed) before
            // validating against the enumeration - real data relies on this (e.g. "left " is a legal
            // NMTOKEN enumeration value, not just "left"). See EnumTypeModel.HasCollapseWhitespaceFacet.
            string parseTarget = e.HasCollapseWhitespaceFacet ? "value.Trim()" : "value";
            using (w.Block($"public static {e.ClrName} Parse(string value) => {parseTarget} switch", "};"))
            {
                foreach (EnumMemberModel m in e.Members)
                    w.Line($"{Lit(m.XmlValue)} => {e.ClrName}.{m.ClrName},");
                w.Line($"_ => throw new FormatException($\"'{{value}}' is not a valid {e.ClrName} value.\"),");
            }
            w.Line();
            using (w.Block($"public static string Format({e.ClrName} value) => value switch", "};"))
            {
                foreach (EnumMemberModel m in e.Members)
                    w.Line($"{e.ClrName}.{m.ClrName} => {Lit(m.XmlValue)},");
                w.Line("_ => throw new ArgumentOutOfRangeException(nameof(value)),");
            }
        }
    }

    // ============================================================================== unions

    private static void EmitUnion(CodeWriter w, UnionTypeModel u, Refs refs)
    {
        // A case only gets a wrapper record when its value type would otherwise collide with another
        // case's in this union (union case types must be pairwise distinct), or when its lexical form
        // is itself an xsd:list (List<ValueClrType>, not ValueClrType, is the real value, which is
        // never eligible for the unwrapped-case optimization - see AssignCaseWrapping). Everything
        // else uses its value type directly as the case, no wrapper needed.
        foreach (UnionCaseModel c in u.Cases.Where(c => c.IsWrapped))
            w.Line($"public sealed record {c.CaseClrName}({(c.IsTokenList ? $"List<{c.ValueClrType}>" : c.ValueClrType)} Value);");
        w.Line();

        if (u.IsElementChoice)
            EmitElementChoiceUnion(w, u, refs);
        else
            EmitTextUnion(w, u, refs);
    }

    /// <summary>
    /// A "custom union type" (the manual form documented for C# 15 unions: a [Union]-attributed
    /// struct implementing IUnion with a public constructor per case and a public Value getter) rather
    /// than the terse `union X(...)` compiler shorthand - the shorthand can't declare extra interfaces,
    /// and this one also implements IXmlSerializable directly, so the whole read/write for an
    /// xsd:choice lives on the union itself: no separate static TryRead/Write companion class. The
    /// compiler still synthesizes implicit case-type conversions, unwrap-to-Value pattern matching, and
    /// exhaustiveness checks for this form exactly as it would for the shorthand, since it only cares
    /// about the [Union] attribute + the basic pattern, not which syntax produced it.
    /// </summary>
    private static void EmitElementChoiceUnion(CodeWriter w, UnionTypeModel u, Refs refs)
    {
        w.Line("[System.Runtime.CompilerServices.Union]");
        using (w.Block($"public partial struct {u.ClrName} : System.Runtime.CompilerServices.IUnion, System.Xml.Serialization.IXmlSerializable"))
        {
            // Not readonly: ReadXml has to be able to set this on an already-constructed (default)
            // instance, the same way the class-typed IXmlSerializable pattern elsewhere in this file
            // does ("new T(); obj.ReadXml(reader);") - a constructor alone can't express "read the
            // reader to find out which case this is".
            w.Line("private object? _value;");
            foreach (UnionCaseModel c in u.Cases)
                w.Line($"public {u.ClrName}({c.CaseClrName} value) => _value = value;");
            w.Line("public object? Value => _value;");
            w.Line();

            w.Line("public System.Xml.Schema.XmlSchema? GetSchema() => null;");
            w.Line();

            using (w.Block("public void ReadXml(XmlReader reader)"))
            {
                using (w.Block("switch (reader.LocalName)"))
                {
                    foreach (UnionCaseModel c in u.Cases)
                    {
                        // A row case whose first member is itself a nested choice has no single leading
                        // element name - fall through from every one of its trigger names into one body.
                        foreach (string name in c.TriggerNames.Take(c.TriggerNames.Count - 1))
                            w.Line($"case {Lit(name)}:");

                        using (w.Block($"case {Lit(c.TriggerNames[c.TriggerNames.Count - 1])}:"))
                        {
                            if (refs.IsRowClass(c.ValueClrType))
                            {
                                w.Line($"var __v = new {c.ValueClrType}();");
                                w.Line("__v.ReadFrom(reader);");
                            }
                            else if (c.IsTokenList)
                            {
                                w.Line($"var __v = new List<{c.ValueClrType}>();");
                                using (w.Block("foreach (var __tok in XsdConvert.SplitList(reader.ReadElementContentAsString()))"))
                                    w.Line($"__v.Add({ParseSingleExpr("__tok", c.ValueIoKind, c.ValueClrType, c.ParseMethod, refs)});");
                            }
                            else
                            {
                                EmitReadSingleLocal(w, "__v", c.ValueIoKind, c.ValueClrType, c.ParseMethod, refs);
                            }
                            w.Line(c.IsWrapped ? $"_value = new {c.CaseClrName}(__v);" : "_value = __v;");
                            w.Line("return;");
                        }
                    }
                    w.Line("default:");
                    using (w.Indented())
                        w.Line($"throw new FormatException($\"'{{reader.LocalName}}' is not a valid element for union '{u.ClrName}'.\");");
                }
            }
            w.Line();

            using (w.Block("public void WriteXml(XmlWriter writer)"))
            {
                // Deliberately an if/is-pattern chain, NOT `switch (this) { case CaseType x: ... }`.
                // A type-pattern switch's exhaustiveness/reachability check is a known Roslyn
                // performance cliff for large case counts (dotnet/roslyn#56230 - pattern matching can
                // be exponential to compile) and this project has real unions with 500+ cases that
                // hang the compiler for over an hour with a switch. An if/else-if chain of plain `is`
                // checks needs none of that whole-statement analysis - verified empirically: the same
                // 680-case shape compiles in ~13s as a chain vs. not finishing in 3+ minutes as a
                // switch, with identical runtime behavior (patterns still unwrap to Value either way).
                //
                // Ordered deepest-inheritance-first, not declaration order: an unwrapped case's `is
                // CaseType` matches any subclass of CaseType too (standard C# type-pattern semantics),
                // and NeTEx substitution groups routinely have one case's value type extend another
                // case's (e.g. FlexibleStopAssignment's type extends StopAssignment's) - checking the
                // ancestor first would silently misclassify every one of its descendants and write the
                // wrong element name for all of them.
                List<UnionCaseModel> orderedCases = [.. u.Cases
                    .Select((c, i) => (Case: c, DeclOrder: i))
                    .OrderByDescending(x => refs.ClassInheritanceDepth(x.Case.CaseClrName))
                    .ThenBy(x => x.DeclOrder)
                    .Select(x => x.Case)];
                for (int i = 0; i < orderedCases.Count; i++)
                {
                    UnionCaseModel c = orderedCases[i];
                    // A pattern variable from `is` is scoped to the rest of the enclosing block, so a
                    // fixed name like "__case" would collide across cases here just like it would in a
                    // switch - same fix as before: a distinct name per case (case types are already
                    // unique within a union, so their camelCased names are too).
                    string caseVar = CSharpIdentifiers.ToCamelIdentifier(c.CaseClrName);
                    string keyword = i == 0 ? "if" : "else if";
                    using (w.Block($"{keyword} (this is {c.CaseClrName} {caseVar})"))
                    {
                        // Wrapped: the case value lives in {caseVar}.Value. Unwrapped: {caseVar}
                        // *is* the value directly (CaseClrName == ValueClrType, no wrapper record).
                        string valueExpr = c.IsWrapped ? $"{caseVar}.Value" : caseVar;
                        if (refs.IsRowClass(c.ValueClrType))
                        {
                            // No wrapping element for a row case - its own elements are the direct content.
                            w.Line($"({valueExpr}).WriteTo(writer);");
                        }
                        else if (c.IsTokenList)
                        {
                            w.Line($"writer.WriteStartElement({Lit(c.ElementXmlName!)}{NsArg(c.ElementXmlNamespace)});");
                            w.Line("var __parts = new List<string>();");
                            using (w.Block($"foreach (var __v in {valueExpr})"))
                                w.Line($"__parts.Add({FormatSingleExpr("__v", c.ValueIoKind, c.ValueClrType, c.FormatMethod, refs)});");
                            w.Line("writer.WriteString(XsdConvert.JoinList(__parts));");
                            w.Line("writer.WriteEndElement();");
                        }
                        else
                        {
                            w.Line($"writer.WriteStartElement({Lit(c.ElementXmlName!)}{NsArg(c.ElementXmlNamespace)});");
                            EmitWriteSingle(w, valueExpr, c.ValueIoKind, c.ValueClrType, c.FormatMethod, refs);
                            w.Line("writer.WriteEndElement();");
                        }
                    }
                }
            }
        }
    }

    /// <summary>
    /// A text union (xsd:union simpleType: a scalar attribute/simpleContent value, never an XML
    /// element in its own right, so IXmlSerializable doesn't apply here) - same custom-union-type
    /// shape as EmitElementChoiceUnion, but with Parse/Format static members directly on the type
    /// instead of ReadXml/WriteXml, again with no separate companion class.
    /// </summary>
    private static void EmitTextUnion(CodeWriter w, UnionTypeModel u, Refs refs)
    {
        w.Line("[System.Runtime.CompilerServices.Union]");
        using (w.Block($"public readonly partial struct {u.ClrName} : System.Runtime.CompilerServices.IUnion"))
        {
            w.Line("private readonly object? _value;");
            foreach (UnionCaseModel c in u.Cases)
                w.Line($"public {u.ClrName}({c.CaseClrName} value) => _value = value;");
            w.Line("public object? Value => _value;");
            w.Line();

            using (w.Block($"public static {u.ClrName} Parse(string value)"))
            {
                w.Line("var errors = new List<Exception>();");
                foreach (UnionCaseModel c in u.Cases)
                {
                    using (w.Block("try"))
                    {
                        string parsed = ParseSingleExpr("value", c.ValueIoKind, c.ValueClrType, c.ParseMethod, refs);
                        w.Line(c.IsWrapped ? $"return new {c.CaseClrName}({parsed});" : $"return {parsed};");
                    }
                    using (w.Block("catch (Exception ex) when (ex is FormatException or OverflowException)"))
                    {
                        w.Line("errors.Add(ex);");
                    }
                }
                w.Line("throw new FormatException(" +
                       $"$\"'{{value}}' did not match any member type of union '{u.ClrName}'.\", new AggregateException(errors));");
            }
            w.Line();
            using (w.Block($"public static string Format({u.ClrName} value) => value switch", "};"))
            {
                foreach (UnionCaseModel c in u.Cases)
                    w.Line($"{c.CaseClrName} c => {FormatSingleExpr(c.IsWrapped ? "c.Value" : "c", c.ValueIoKind, c.ValueClrType, c.FormatMethod, refs)},");
                w.Line("_ => throw new ArgumentOutOfRangeException(nameof(value)),");
            }
        }
    }

    // ============================================================================== classes

    private static void EmitClass(CodeWriter w, ClassTypeModel c, Refs refs)
    {
        if (c.IsRow)
        {
            EmitRowClass(w, c, refs);
            return;
        }

        if (c.BaseClass is null && !refs.HasSubclasses(c) && !c.IsAbstract)
        {
            // The common case (no xsd:complexContent extension involved anywhere in this type's
            // family, and not itself abstract): identical to the original single-class shape, so
            // leave it untouched.
            EmitXmlRootAttributeIfAny(w, c.ClrName, refs);
            using (w.Block($"public sealed partial class {c.ClrName} : System.Xml.Serialization.IXmlSerializable"))
            {
                foreach (MemberModel a in c.Attributes)
                    EmitProperty(w, a);
                foreach (MemberModel e in c.Elements)
                    EmitProperty(w, e);
                if (c.SimpleContent is { } sc)
                    EmitProperty(w, sc);
                if (c.IsMixed)
                    w.Line("public string? MixedText { get; set; }");

                w.Line();
                w.Line("public System.Xml.Schema.XmlSchema? GetSchema() => null;");
                w.Line();

                EmitClassWriteXml(w, c, refs);
                w.Line();
                EmitClassReadXml(w, c, refs);
            }
            return;
        }

        EmitInheritedClass(w, c, refs);
    }

    /// <summary>
    /// A class that participates in an xsd:complexContent extension chain (either as a base, a leaf,
    /// or a middle link) and/or is itself abstract (XSD complexType abstract="true"): a real C#
    /// base/derived relationship, with a single non-virtual ReadXml/WriteXml pair living on the
    /// hierarchy's root (BaseClass is null) that drives a set of protected virtual "own content"
    /// hooks each level overrides - so no level re-reads/re-writes members that actually live on a
    /// different class in the chain. Abstract classes need this same virtual-hook shape even when
    /// standalone (no base, no subclasses in this schema), since they still need concrete
    /// ReadXml/WriteXml entry points usable by whatever ends up extending them. Only classes touched
    /// by inheritance or abstractness pay for this extra shape; see the plain-class path in
    /// <see cref="EmitClass"/>.
    /// </summary>
    private static void EmitInheritedClass(CodeWriter w, ClassTypeModel c, Refs refs)
    {
        bool hasBase = c.BaseClass is not null;
        // abstract and sealed are mutually exclusive in C# - an IsAbstract type is never sealed,
        // regardless of whether anything in this schema actually extends it.
        string classModifier = c.IsAbstract ? "abstract " : refs.HasSubclasses(c) ? "" : "sealed ";
        string header = hasBase
            ? $"public {classModifier}partial class {c.ClrName} : {c.BaseClass!.ClrName}"
            : $"public {classModifier}partial class {c.ClrName} : System.Xml.Serialization.IXmlSerializable";

        EmitXmlRootAttributeIfAny(w, c.ClrName, refs);
        using (w.Block(header))
        {
            foreach (MemberModel a in c.Attributes)
                EmitProperty(w, a);
            foreach (MemberModel e in c.Elements)
                EmitProperty(w, e);
            if (c.SimpleContent is { } scProp)
                EmitProperty(w, scProp);
            w.Line();

            if (!hasBase)
            {
                w.Line("public System.Xml.Schema.XmlSchema? GetSchema() => null;");
                w.Line();
                if (c.SimpleContent is { } sc)
                {
                    // simpleContent (attributes + text, no child elements) that also has a subclass
                    // in this schema - NeTEx's pervasive "<XRef><complexContent><extension
                    // base="XRefStructure"/>" idiom, an empty complexContent extension used purely to
                    // give a shared simpleContent type a distinct named element, adding no content of
                    // its own. XSD disallows a complexContent extension of a simpleContent base from
                    // adding new elements, so c.Elements is always empty here - WriteXmlElements/
                    // TryReadXmlElement (the element-name-dispatch hooks below) don't apply to text
                    // content at all, so this reads/writes the text directly instead, the same way
                    // EmitClassWriteXml/EmitClassReadXml do for a simpleContent type with no
                    // inheritance involved - only WriteXmlAttributes/ReadXmlAttributes are still
                    // routed through the normal virtual chain, since attributes remain per-level.
                    using (w.Block("public void WriteXml(XmlWriter writer)"))
                    {
                        w.Line("WriteXmlAttributes(writer);");
                        if (sc.IsTokenList)
                        {
                            w.Line("var __parts = new List<string>();");
                            using (w.Block($"foreach (var __v in this.{sc.ClrPropertyName})"))
                                w.Line($"__parts.Add({FormatSingleExpr("__v", sc.IoKind, sc.ClrTypeName, sc.FormatMethod, refs)});");
                            w.Line("writer.WriteString(XsdConvert.JoinList(__parts));");
                        }
                        else
                        {
                            w.Line($"writer.WriteString({FormatSingleExpr(AccessExpr(sc), sc.IoKind, sc.ClrTypeName, sc.FormatMethod, refs)});");
                        }
                    }
                    w.Line();
                    using (w.Block("public void ReadXml(XmlReader reader)"))
                    {
                        w.Line("ReadXmlAttributes(reader);");
                        if (sc.IsTokenList)
                        {
                            using (w.Block("foreach (var __tok in XsdConvert.SplitList(reader.ReadElementContentAsString()))"))
                                w.Line($"this.{sc.ClrPropertyName}.Add({ParseSingleExpr("__tok", sc.IoKind, sc.ClrTypeName, sc.ParseMethod, refs)});");
                        }
                        else
                        {
                            w.Line($"this.{sc.ClrPropertyName} = {ParseSingleExpr("reader.ReadElementContentAsString()", sc.IoKind, sc.ClrTypeName, sc.ParseMethod, refs)};");
                        }
                    }
                    w.Line();
                }
                else
                {
                    using (w.Block("public void WriteXml(XmlWriter writer)"))
                    {
                        w.Line("WriteXmlAttributes(writer);");
                        w.Line("WriteXmlElements(writer);");
                    }
                    w.Line();
                    using (w.Block("public void ReadXml(XmlReader reader)"))
                    {
                        w.Line("ReadXmlAttributes(reader);");
                        using (w.Block("if (reader.IsEmptyElement)"))
                            w.Line("reader.ReadStartElement();");
                        using (w.Block("else"))
                        {
                            w.Line("reader.ReadStartElement();");
                            using (w.Block("while (reader.NodeType != XmlNodeType.EndElement)"))
                            {
                                using (w.Block("if (reader.NodeType != XmlNodeType.Element)"))
                                {
                                    w.Line("reader.Read();");
                                    w.Line("continue;");
                                }
                                using (w.Block("if (!TryReadXmlElement(reader) && !TryReadXmlWildcard(reader))"))
                                    w.Line("reader.Skip();");
                            }
                            w.Line("reader.ReadEndElement();");
                        }
                    }
                    w.Line();
                }
            }

            string? modifier = hasBase ? "override" : "virtual";

            using (w.Block($"protected {modifier} void WriteXmlAttributes(XmlWriter writer)"))
            {
                if (hasBase) w.Line("base.WriteXmlAttributes(writer);");
                foreach (MemberModel a in c.Attributes)
                    EmitWriteAttribute(w, a, refs);
            }
            w.Line();

            using (w.Block($"protected {modifier} void WriteXmlElements(XmlWriter writer)"))
            {
                if (hasBase) w.Line("base.WriteXmlElements(writer);");
                foreach (MemberModel el in c.Elements)
                    EmitWriteElement(w, el, refs);
            }
            w.Line();

            using (w.Block($"protected {modifier} void ReadXmlAttributes(XmlReader reader)"))
            {
                if (hasBase) w.Line("base.ReadXmlAttributes(reader);");
                foreach (MemberModel a in c.Attributes)
                    EmitReadAttribute(w, a, refs);
            }
            w.Line();

            using (w.Block($"protected {modifier} bool TryReadXmlElement(XmlReader reader)"))
                EmitTryReadXmlElementBody(w, c.Elements, refs, hasBase);
            w.Line();

            using (w.Block($"protected {modifier} bool TryReadXmlWildcard(XmlReader reader)"))
            {
                MemberModel? wildcard = c.Elements.FirstOrDefault(e => e.IoKind == IoKind.Wildcard);
                if (wildcard is not null)
                {
                    w.Line("var __anyDoc = new XmlDocument();");
                    // ReadSubtree()'s reader must be disposed before the outer reader's position is
                    // trustworthy again: per XmlReader docs, closing it only advances the outer reader
                    // to the wildcard element's own end tag (not past it), so an explicit Read() after
                    // disposal is still required to reach the next sibling. Skipping disposal entirely
                    // (as a naive inline `ReadNode(reader.ReadSubtree())` does) leaves the outer reader
                    // sitting ON the end tag, which every enclosing read loop then mistakes for its own
                    // closing tag - silently truncating everything that follows.
                    using (w.Block("using (var __subtreeReader = reader.ReadSubtree())"))
                        w.Line($"this.{wildcard.ClrPropertyName}.Add((XmlElement)__anyDoc.ReadNode(__subtreeReader)!);");
                    w.Line("reader.Read();");
                    w.Line("return true;");
                }
                else
                {
                    w.Line(hasBase ? "return base.TryReadXmlWildcard(reader);" : "return false;");
                }
            }
        }
    }

    /// <summary>
    /// Body of an inherited class's TryReadXmlElement: switch over this level's own element names
    /// (plain and choice-union members alike - see EmitElementDispatchBody), and finally either
    /// delegating to the base class's own members (hasBase) or giving up (root of the chain).
    /// Wildcard capture is handled separately by TryReadXmlWildcard, not here.
    /// </summary>
    private static void EmitTryReadXmlElementBody(CodeWriter w, List<MemberModel> ownElements, Refs refs, bool hasBase)
    {
        List<MemberModel> namedMembers = [.. ownElements.Where(e => e.IoKind != IoKind.Wildcard)];

        if (namedMembers.Count > 0)
        {
            using (w.Block("switch (reader.LocalName)"))
            {
                foreach (MemberModel el in namedMembers)
                {
                    List<string> triggerNames = MemberTriggerNames(el, refs);
                    foreach (string name in triggerNames.Take(triggerNames.Count - 1))
                        w.Line($"case {Lit(name)}:");

                    using (w.Block($"case {Lit(triggerNames[triggerNames.Count - 1])}:"))
                    {
                        EmitReadElementCase(w, el, refs);
                        w.Line("return true;");
                    }
                }
            }
        }

        w.Line(hasBase ? "return base.TryReadXmlElement(reader);" : "return false;");
    }

    /// <summary>
    /// A "row" class for a multi-element xsd:choice branch: no wrapping element of its own, so instead
    /// of IXmlSerializable it gets bare ReadFrom/WriteTo that read/write its elements directly, bounded
    /// by a known-name-set check rather than a start/end element pair.
    /// </summary>
    private static void EmitRowClass(CodeWriter w, ClassTypeModel c, Refs refs)
    {
        using (w.Block($"public sealed partial class {c.ClrName}"))
        {
            foreach (MemberModel e in c.Elements)
                EmitProperty(w, e);
            w.Line();

            IEnumerable<string> triggerNames = CollectTriggerNames(c.Elements, refs);
            w.Line($"private static readonly HashSet<string> s_elementNames = new() {{ {string.Join(", ", triggerNames.Select(Lit))} }};");
            // Names that can only legally appear once per row instance: seeing one again means a new
            // row has started (this matters when a row is used repeatedly, e.g. List<Row> - without
            // this, one row's ReadFrom would greedily swallow the next row's elements too since they
            // share the same names). Members that are themselves individually repeating are excluded,
            // since re-seeing their name is expected within a single row instance.
            IEnumerable<string> singleOccurrenceNames = CollectTriggerNames([.. c.Elements.Where(e => !e.IsRepeating)], refs);
            w.Line($"private static readonly HashSet<string> s_singleOccurrenceNames = new() {{ {string.Join(", ", singleOccurrenceNames.Select(Lit))} }};");
            w.Line();

            using (w.Block("public void WriteTo(XmlWriter writer)"))
            {
                foreach (MemberModel el in c.Elements)
                    EmitWriteElement(w, el, refs);
            }
            w.Line();

            using (w.Block("public void ReadFrom(XmlReader reader)"))
            {
                w.Line("var __seen = new HashSet<string>();");
                using (w.Block("while (true)"))
                {
                    using (w.Block("if (reader.NodeType != XmlNodeType.Element)"))
                    {
                        using (w.Block("if (reader.NodeType == XmlNodeType.EndElement || reader.EOF)"))
                            w.Line("break;");
                        w.Line("reader.Read();");
                        w.Line("continue;");
                    }
                    using (w.Block("if (!s_elementNames.Contains(reader.LocalName))"))
                        w.Line("break;");
                    using (w.Block("if (s_singleOccurrenceNames.Contains(reader.LocalName) && !__seen.Add(reader.LocalName))"))
                        w.Line("break;");

                    EmitElementDispatchBody(w, c.Elements, refs);
                }
            }
        }
    }

    private static void EmitProperty(CodeWriter w, MemberModel m)
    {
        if (m.IsRepeating && m.IsTokenList)
        {
            w.Line($"public List<List<{m.ClrTypeName}>> {m.ClrPropertyName} {{ get; set; }} = new();");
        }
        else if (m.IsRepeating || m.IsTokenList)
        {
            w.Line($"public List<{m.ClrTypeName}> {m.ClrPropertyName} {{ get; set; }} = new();");
        }
        else if (m.IsOptional)
        {
            w.Line($"public {m.ClrTypeName}? {m.ClrPropertyName} {{ get; set; }}");
        }
        else if (m.IsValueType)
        {
            w.Line($"public {m.ClrTypeName} {m.ClrPropertyName} {{ get; set; }}");
        }
        else
        {
            w.Line($"public {m.ClrTypeName} {m.ClrPropertyName} {{ get; set; }} = default!;");
        }
    }

    private static void EmitClassWriteXml(CodeWriter w, ClassTypeModel c, Refs refs)
    {
        using (w.Block("public void WriteXml(XmlWriter writer)"))
        {
            foreach (MemberModel a in c.Attributes)
                EmitWriteAttribute(w, a, refs);

            if (c.SimpleContent is { } sc)
            {
                if (sc.IsTokenList)
                {
                    w.Line("var __parts = new List<string>();");
                    using (w.Block($"foreach (var __v in this.{sc.ClrPropertyName})"))
                        w.Line($"__parts.Add({FormatSingleExpr("__v", sc.IoKind, sc.ClrTypeName, sc.FormatMethod, refs)});");
                    w.Line("writer.WriteString(XsdConvert.JoinList(__parts));");
                }
                else
                {
                    w.Line($"writer.WriteString({FormatSingleExpr(AccessExpr(sc), sc.IoKind, sc.ClrTypeName, sc.FormatMethod, refs)});");
                }
                return;
            }

            // mixed="true": the deprecated-but-still-common "plain text instead of child elements"
            // form (see ClassTypeModel.IsMixed) - written before any element children since real
            // instances only ever use one form or the other, never genuinely both at once.
            if (c.IsMixed)
                using (w.Block("if (this.MixedText is not null)"))
                    w.Line("writer.WriteString(this.MixedText);");

            foreach (MemberModel el in c.Elements)
                EmitWriteElement(w, el, refs);
        }
    }

    private static void EmitWriteAttribute(CodeWriter w, MemberModel a, Refs refs)
    {
        Action body = new(() =>
        {
            if (a.IsTokenList)
            {
                w.Line("{");
                using (w.Indented())
                {
                    w.Line("var __parts = new List<string>();");
                    using (w.Block($"foreach (var __v in this.{a.ClrPropertyName})"))
                        w.Line($"__parts.Add({FormatSingleExpr("__v", a.IoKind, a.ClrTypeName, a.FormatMethod, refs)});");
                    w.Line($"writer.WriteAttributeString({Lit(a.XmlName)}{NsArg(a.XmlNamespace)}, XsdConvert.JoinList(__parts));");
                }
                w.Line("}");
            }
            else
            {
                w.Line($"writer.WriteAttributeString({Lit(a.XmlName)}{NsArg(a.XmlNamespace)}, " +
                       $"{FormatSingleExpr(AccessExpr(a), a.IoKind, a.ClrTypeName, a.FormatMethod, refs)});");
            }
        });

        string? check = PresenceCheck(a);
        if (check is null)
        {
            body();
        }
        else
        {
            using (w.Block($"if ({check})"))
                body();
        }
    }

    private static void EmitWriteElement(CodeWriter w, MemberModel el, Refs refs)
    {
        if (el.IoKind == IoKind.Wildcard)
        {
            // Each captured element already carries its own name/markup - write it verbatim, no wrapping.
            using (w.Block($"foreach (var __any in this.{el.ClrPropertyName})"))
                w.Line("__any.WriteTo(writer);");
            return;
        }

        if (refs.IsChoiceUnion(el.ClrTypeName))
        {
            // The union's own WriteXml (it implements IXmlSerializable directly - see
            // EmitElementChoiceUnion) writes the *whole* element itself, including start/end tags,
            // since the element name/namespace depends on whichever case is active - unlike a class
            // member, the caller here does no wrapping of its own.
            if (el.IsRepeating)
            {
                using (w.Block($"foreach (var __item in this.{el.ClrPropertyName})"))
                    w.Line("__item.WriteXml(writer);");
            }
            else if (el.IsOptional)
            {
                // Not `is {} x`: pattern variables from `is` are scoped to the whole enclosing method
                // body (not just this if), so a fixed name would collide across sibling members: and
                // for a union struct specifically, `is {}` binds to the union's underlying Value
                // (object?) rather than the union itself in this preview compiler - `is not null` +
                // AccessExpr's own .Value unwrapping sidesteps both problems.
                using (w.Block($"if (this.{el.ClrPropertyName} is not null)"))
                    w.Line($"({AccessExpr(el)}).WriteXml(writer);");
            }
            else
            {
                w.Line($"this.{el.ClrPropertyName}.WriteXml(writer);");
            }
            return;
        }

        if (el.IsRepeating && el.IsTokenList)
        {
            // List<List<T>>: one sibling element per outer entry, each one's text is its own inner list.
            using (w.Block($"foreach (var __outer in this.{el.ClrPropertyName})"))
            {
                w.Line("var __parts = new List<string>();");
                using (w.Block("foreach (var __v in __outer)"))
                    w.Line($"__parts.Add({FormatSingleExpr("__v", el.IoKind, el.ClrTypeName, el.FormatMethod, refs)});");
                w.Line($"writer.WriteElementString({Lit(el.XmlName)}{NsArg(el.XmlNamespace)}, XsdConvert.JoinList(__parts));");
            }
            return;
        }

        if (el.IsTokenList)
        {
            string? check = PresenceCheck(el);
            void Body()
            {
                w.Line("{");
                using (w.Indented())
                {
                    w.Line("var __parts = new List<string>();");
                    using (w.Block($"foreach (var __v in this.{el.ClrPropertyName})"))
                        w.Line($"__parts.Add({FormatSingleExpr("__v", el.IoKind, el.ClrTypeName, el.FormatMethod, refs)});");
                    w.Line($"writer.WriteElementString({Lit(el.XmlName)}{NsArg(el.XmlNamespace)}, XsdConvert.JoinList(__parts));");
                }
                w.Line("}");
            }
            if (check is null) Body();
            else using (w.Block($"if ({check})")) Body();
            return;
        }

        if (el.IsRepeating)
        {
            using (w.Block($"foreach (var __item in this.{el.ClrPropertyName})"))
                EmitWriteSingleElement(w, "__item", el, refs);
            return;
        }

        if (el.IsOptional)
        {
            // See the comment in EmitWriteElement's choice-union branch: avoid `is {} x` here too.
            if (el.IsNillable)
            {
                using (w.Block($"if (this.{el.ClrPropertyName} is not null)"))
                    EmitWriteSingleElement(w, AccessExpr(el), el, refs);
                using (w.Block("else"))
                {
                    w.Line($"writer.WriteStartElement({Lit(el.XmlName)}{NsArg(el.XmlNamespace)});");
                    w.Line($"writer.WriteAttributeString(\"nil\", {Lit(XsiNs)}, \"true\");");
                    w.Line("writer.WriteEndElement();");
                }
            }
            else
            {
                using (w.Block($"if (this.{el.ClrPropertyName} is not null)"))
                    EmitWriteSingleElement(w, AccessExpr(el), el, refs);
            }
            return;
        }

        EmitWriteSingleElement(w, $"this.{el.ClrPropertyName}", el, refs);
    }

    private static void EmitWriteSingleElement(CodeWriter w, string valueExpr, MemberModel el, Refs refs)
    {
        if (refs.IsRowClass(el.ClrTypeName))
        {
            // No wrapping element for a row - its own elements are the direct content.
            w.Line($"({valueExpr}).WriteTo(writer);");
        }
        else if (refs.IsClass(el.ClrTypeName))
        {
            w.Line($"writer.WriteStartElement({Lit(el.XmlName)}{NsArg(el.XmlNamespace)});");
            w.Line($"({valueExpr}).WriteXml(writer);");
            w.Line("writer.WriteEndElement();");
        }
        else
        {
            w.Line($"writer.WriteElementString({Lit(el.XmlName)}{NsArg(el.XmlNamespace)}, " +
                   $"{FormatSingleExpr(valueExpr, el.IoKind, el.ClrTypeName, el.FormatMethod, refs)});");
        }
    }

    private static void EmitWriteSingle(CodeWriter w, string valueExpr, IoKind ioKind, string clrTypeName, string? formatMethod, Refs refs)
    {
        // Used for union-case values that live directly inside a caller-written wrapping element.
        if (ioKind == IoKind.Serializable && refs.IsClass(clrTypeName))
        {
            w.Line($"({valueExpr}).WriteXml(writer);");
        }
        else
        {
            w.Line($"writer.WriteString({FormatSingleExpr(valueExpr, ioKind, clrTypeName, formatMethod, refs)});");
        }
    }

    private static void EmitClassReadXml(CodeWriter w, ClassTypeModel c, Refs refs)
    {
        using (w.Block("public void ReadXml(XmlReader reader)"))
        {
            foreach (MemberModel a in c.Attributes)
                EmitReadAttribute(w, a, refs);

            if (c.SimpleContent is { } sc)
            {
                if (sc.IsTokenList)
                {
                    using (w.Block("foreach (var __tok in XsdConvert.SplitList(reader.ReadElementContentAsString()))"))
                        w.Line($"this.{sc.ClrPropertyName}.Add({ParseSingleExpr("__tok", sc.IoKind, sc.ClrTypeName, sc.ParseMethod, refs)});");
                }
                else
                {
                    w.Line($"this.{sc.ClrPropertyName} = {ParseSingleExpr("reader.ReadElementContentAsString()", sc.IoKind, sc.ClrTypeName, sc.ParseMethod, refs)};");
                }
                return;
            }

            using (w.Block("if (reader.IsEmptyElement)"))
                w.Line("reader.ReadStartElement();");
            using (w.Block("else"))
            {
                w.Line("reader.ReadStartElement();");
                using (w.Block("while (reader.NodeType != XmlNodeType.EndElement)"))
                {
                    using (w.Block("if (reader.NodeType != XmlNodeType.Element)"))
                    {
                        // mixed="true" content can carry free-floating text/CDATA runs alongside its
                        // element children (see ClassTypeModel.IsMixed) - captured here since, unlike
                        // an ordinary child element, they have no name to dispatch on. Pure indentation
                        // whitespace between elements is reported as XmlNodeType.Whitespace, not Text,
                        // so it's excluded without needing an explicit check.
                        if (c.IsMixed)
                            using (w.Block("if (reader.NodeType is XmlNodeType.Text or XmlNodeType.CDATA)"))
                                w.Line("this.MixedText = (this.MixedText ?? \"\") + reader.Value;");
                        w.Line("reader.Read();");
                        w.Line("continue;");
                    }

                    EmitElementDispatchBody(w, c.Elements, refs);
                }
                w.Line("reader.ReadEndElement();");
            }
        }
    }

    /// <summary>
    /// The shared switch-on-reader.LocalName dispatch body used by both a normal class's ReadXml
    /// (which loops "until EndElement") and a row's bounded ReadFrom (which loops "until the next
    /// element isn't one of mine"). Both callers are already positioned at a start element when
    /// this runs and are responsible for advancing past whatever this dispatches to. A choice-union
    /// member's own case names route into the same switch as plain elements - the union's own
    /// ReadXml (it implements IXmlSerializable directly, see EmitElementChoiceUnion) resolves which
    /// case actually matched, so this dispatch only needs to know a name belongs to that member at all.
    /// </summary>
    private static void EmitElementDispatchBody(CodeWriter w, List<MemberModel> elements, Refs refs)
    {
        MemberModel? wildcardMember = elements.FirstOrDefault(e => e.IoKind == IoKind.Wildcard);
        List<MemberModel> namedMembers = [.. elements.Where(e => e.IoKind != IoKind.Wildcard)];

        if (namedMembers.Count > 0)
        {
            using (w.Block("switch (reader.LocalName)"))
            {
                HashSet<string> claimedNames = new(StringComparer.Ordinal);
                foreach (MemberModel el in namedMembers)
                {
                    // Two different members can legitimately claim the same element name in this
                    // simplified (name-only, not full XSD content-model-position-aware) dispatch - e.g.
                    // a plain xsd:choice member and a separate substitution-group member that happens to
                    // share one of its substitutes. A duplicate `case` label is a compile error, so
                    // whichever member is declared first here claims the name; this reproduces exactly
                    // what the old runtime-probing design already did silently (try candidates in
                    // declaration order, first match wins) at codegen time instead.
                    List<string> triggerNames = [.. MemberTriggerNames(el, refs).Where(claimedNames.Add)];
                    if (triggerNames.Count == 0)
                        continue;

                    // A row member whose first sub-member is itself a nested choice (or a choice-union
                    // member with more than one case) has multiple possible leading names - fall
                    // through from all of them into one body.
                    foreach (string name in triggerNames.Take(triggerNames.Count - 1))
                        w.Line($"case {Lit(name)}:");

                    using (w.Block($"case {Lit(triggerNames[triggerNames.Count - 1])}:"))
                    {
                        EmitReadElementCase(w, el, refs);
                        w.Line("break;");
                    }
                }
                w.Line("default:");
                using (w.Indented())
                {
                    EmitWildcardFallback(w, wildcardMember);
                    w.Line("break;");
                }
            }
        }
        else
        {
            EmitWildcardFallback(w, wildcardMember);
        }
    }

    /// <summary>
    /// The concrete XML element local name(s) that route a read dispatch to this member: its own
    /// TriggerNames, or - for a choice-union member, which has no element name of its own - every one
    /// of its cases' element names (the union's own ReadXml figures out internally which case matched;
    /// the caller just needs to know the name belongs to this member at all).
    /// </summary>
    private static List<string> MemberTriggerNames(MemberModel el, Refs refs) =>
        refs.IsChoiceUnion(el.ClrTypeName)
            ? [.. refs.Unions[el.ClrTypeName].Cases.SelectMany(c => c.TriggerNames)]
            : el.TriggerNames;

    /// <summary>The set of concrete XML element local names that could legally appear next for the given member list.</summary>
    private static IEnumerable<string> CollectTriggerNames(List<MemberModel> elements, Refs refs) =>
        elements.Where(e => e.IoKind != IoKind.Wildcard).SelectMany(e => MemberTriggerNames(e, refs));

    /// <summary>The terminal fallback for a name that matched no known member at all: capture into the xsd:any bucket if there is one, else skip it.</summary>
    private static void EmitWildcardFallback(CodeWriter w, MemberModel? wildcardMember)
    {
        if (wildcardMember is null)
        {
            w.Line("reader.Skip();");
        }
        else
        {
            w.Line("var __anyDoc = new XmlDocument();");
            // See the matching comment in EmitInheritedClass's TryReadXmlWildcard emission: the
            // subtree reader must be disposed, then the outer reader advanced one more step, or the
            // caller's own end-of-loop check mistakes the wildcard element's end tag for its own.
            using (w.Block("using (var __subtreeReader = reader.ReadSubtree())"))
                w.Line($"this.{wildcardMember.ClrPropertyName}.Add((XmlElement)__anyDoc.ReadNode(__subtreeReader)!);");
            w.Line("reader.Read();");
        }
    }

    private static void EmitReadElementCase(CodeWriter w, MemberModel el, Refs refs)
    {
        if (el.IsNillable)
        {
            using (w.Block($"if (reader.GetAttribute(\"nil\", {Lit(XsiNs)}) == \"true\")"))
                w.Line("reader.Skip();");
            using (w.Block("else"))
                EmitReadElementCaseBody(w, el, refs);
        }
        else
        {
            EmitReadElementCaseBody(w, el, refs);
        }
    }

    private static void EmitReadElementCaseBody(CodeWriter w, MemberModel el, Refs refs)
    {
        if (el.IsRepeating && el.IsTokenList)
        {
            // One inner List<T> per sibling element occurrence.
            w.Line($"var __inner = new List<{el.ClrTypeName}>();");
            using (w.Block("foreach (var __tok in XsdConvert.SplitList(reader.ReadElementContentAsString()))"))
                w.Line($"__inner.Add({ParseSingleExpr("__tok", el.IoKind, el.ClrTypeName, el.ParseMethod, refs)});");
            w.Line($"this.{el.ClrPropertyName}.Add(__inner);");
        }
        else if (el.IsTokenList)
        {
            using (w.Block($"foreach (var __tok in XsdConvert.SplitList(reader.ReadElementContentAsString()))"))
                w.Line($"this.{el.ClrPropertyName}.Add({ParseSingleExpr("__tok", el.IoKind, el.ClrTypeName, el.ParseMethod, refs)});");
        }
        else if (refs.IsRowClass(el.ClrTypeName))
        {
            w.Line($"var __obj = new {el.ClrTypeName}();");
            w.Line("__obj.ReadFrom(reader);");
            w.Line(el.IsRepeating ? $"this.{el.ClrPropertyName}.Add(__obj);" : $"this.{el.ClrPropertyName} = __obj;");
        }
        else if (refs.IsClass(el.ClrTypeName) || refs.IsChoiceUnion(el.ClrTypeName))
        {
            // A choice-union member's own ReadXml (it implements IXmlSerializable directly) figures
            // out internally which of its cases the current element is - same call shape as a class.
            w.Line($"var __obj = new {el.ClrTypeName}();");
            w.Line("__obj.ReadXml(reader);");
            w.Line(el.IsRepeating ? $"this.{el.ClrPropertyName}.Add(__obj);" : $"this.{el.ClrPropertyName} = __obj;");
        }
        else
        {
            // XSD's default="..."/fixed="..." applies when the element is present but empty (e.g.
            // "<HasMinimumPrice/>" with default="false" means false) - distinct from the element being
            // omitted entirely. See MemberModel.XsdDefaultValue.
            string rawExpr = el.XsdDefaultValue is null
                ? "reader.ReadElementContentAsString()"
                : $"XsdConvert.DefaultIfEmpty(reader.ReadElementContentAsString(), {Lit(el.XsdDefaultValue)})";
            string expr = ParseSingleExpr(rawExpr, el.IoKind, el.ClrTypeName, el.ParseMethod, refs);
            w.Line(el.IsRepeating ? $"this.{el.ClrPropertyName}.Add({expr});" : $"this.{el.ClrPropertyName} = {expr};");
        }
    }

    private static void EmitReadAttribute(CodeWriter w, MemberModel a, Refs refs)
    {
        w.Line("{");
        using (w.Indented())
        {
            w.Line($"var __raw = reader.GetAttribute({Lit(a.XmlName)}{NsArg(a.XmlNamespace)});");
            using (w.Block("if (__raw is not null)"))
            {
                if (a.IsTokenList)
                {
                    using (w.Block("foreach (var __tok in XsdConvert.SplitList(__raw))"))
                        w.Line($"this.{a.ClrPropertyName}.Add({ParseSingleExpr("__tok", a.IoKind, a.ClrTypeName, a.ParseMethod, refs)});");
                }
                else
                {
                    // Same default="..."/fixed="..." handling as elements - see MemberModel.XsdDefaultValue.
                    // (Strictly, XSD only applies an attribute's default when it's omitted, not when
                    // given as an explicit empty string - but treating an explicit "" the same way is
                    // simpler and safer than failing to parse it, consistent with this generator's
                    // general leniency toward messy real-world data.)
                    string rawExpr = a.XsdDefaultValue is null ? "__raw" : $"XsdConvert.DefaultIfEmpty(__raw, {Lit(a.XsdDefaultValue)})";
                    w.Line($"this.{a.ClrPropertyName} = {ParseSingleExpr(rawExpr, a.IoKind, a.ClrTypeName, a.ParseMethod, refs)};");
                }
            }
        }
        w.Line("}");
    }

    /// <summary>Declares and reads a local `var {localVarName} = ...;` of the given value type from the current element.</summary>
    private static void EmitReadSingleLocal(CodeWriter w, string localVarName, IoKind ioKind, string clrTypeName, string? parseMethod, Refs refs)
    {
        if (ioKind == IoKind.Serializable && refs.IsClass(clrTypeName))
        {
            w.Line($"var {localVarName} = new {clrTypeName}();");
            w.Line($"{localVarName}.ReadXml(reader);");
        }
        else
        {
            w.Line($"var {localVarName} = {ParseSingleExpr("reader.ReadElementContentAsString()", ioKind, clrTypeName, parseMethod, refs)};");
        }
    }

    private static void EmitRootDocuments(CodeWriter w, IEnumerable<RootElementModel> rootElements, Refs refs)
    {
        HashSet<string> usedNames = new(StringComparer.Ordinal);
        foreach (RootElementModel root in rootElements)
        {
            string helperName = CSharpIdentifiers.Uniquify(CSharpIdentifiers.ToPascalIdentifier(root.XmlName) + "Document", usedNames);

            using (w.Block($"public static class {helperName}"))
            {
                w.Line($"public const string ElementName = {Lit(root.XmlName)};");
                w.Line($"public const string ElementNamespace = {Lit(root.XmlNamespace ?? "")};");
                w.Line();

                using (w.Block($"public static {root.ClrTypeName} Load(XmlReader reader)"))
                {
                    w.Line("reader.MoveToContent();");
                    if (refs.IsClass(root.ClrTypeName))
                    {
                        w.Line($"var obj = new {root.ClrTypeName}();");
                        w.Line("obj.ReadXml(reader);");
                        w.Line("return obj;");
                    }
                    else
                    {
                        IoKind ioKind = refs.Enums.ContainsKey(root.ClrTypeName) ? IoKind.Enum
                            : refs.Unions.ContainsKey(root.ClrTypeName) ? IoKind.Serializable
                            : IoKind.Primitive;
                        w.Line($"var value = {ParseSingleExpr("reader.ReadElementContentAsString()", ioKind, root.ClrTypeName, root.ParseMethod, refs)};");
                        w.Line("return value;");
                    }
                }
                w.Line();

                using (w.Block($"public static void Save(XmlWriter writer, {root.ClrTypeName} value)"))
                {
                    if (refs.IsClass(root.ClrTypeName))
                    {
                        w.Line("writer.WriteStartElement(ElementName, ElementNamespace);");
                        w.Line("value.WriteXml(writer);");
                        w.Line("writer.WriteEndElement();");
                    }
                    else
                    {
                        IoKind ioKind = refs.Enums.ContainsKey(root.ClrTypeName) ? IoKind.Enum
                            : refs.Unions.ContainsKey(root.ClrTypeName) ? IoKind.Serializable
                            : IoKind.Primitive;
                        w.Line($"writer.WriteElementString(ElementName, ElementNamespace, {FormatSingleExpr("value", ioKind, root.ClrTypeName, root.FormatMethod, refs)});");
                    }
                }
            }
            w.Line();
        }
    }

    private static string AccessExpr(MemberModel m) =>
        // Optional value-type (non-collection) members are Nullable<T> properties; everywhere this is
        // used, the caller has already established presence (see PresenceCheck), so .Value is safe.
        m.IsOptional && m.IsValueType && !m.IsRepeating && !m.IsTokenList
            ? $"this.{m.ClrPropertyName}.Value"
            : $"this.{m.ClrPropertyName}";

    private static string? PresenceCheck(MemberModel m)
    {
        if (m.IsRepeating || m.IsTokenList)
            return $"this.{m.ClrPropertyName}.Count > 0";
        if (m.IsOptional)
            return m.IsValueType ? $"this.{m.ClrPropertyName}.HasValue" : $"this.{m.ClrPropertyName} is not null";
        return null;
    }

    private static string FormatSingleExpr(string valueExpr, IoKind ioKind, string clrTypeName, string? formatMethod, Refs refs) => ioKind switch
    {
        IoKind.Primitive => formatMethod is null ? valueExpr : $"XsdConvert.{formatMethod}({valueExpr})",
        IoKind.Enum => $"{clrTypeName}Xml.Format({valueExpr})",
        // Serializable + Format/Parse-as-a-string only ever applies to text unions (xsd:union
        // simpleType) - an element-choice union is never used as a bare scalar value, always as an
        // actual element (see EmitElementChoiceUnion's ReadXml/WriteXml), and a class-typed value is
        // always intercepted before reaching here (every call site gates on refs.IsClass first). Text
        // unions carry Parse/Format directly as static members on the union type itself, no separate
        // companion class - see EmitTextUnion.
        IoKind.Serializable => $"{clrTypeName}.Format({valueExpr})",
        _ => valueExpr,
    };

    private static string ParseSingleExpr(string textExpr, IoKind ioKind, string clrTypeName, string? parseMethod, Refs refs) => ioKind switch
    {
        IoKind.Primitive => parseMethod is null ? textExpr : $"XsdConvert.{parseMethod}({textExpr})",
        IoKind.Enum => $"{clrTypeName}Xml.Parse({textExpr})",
        IoKind.Serializable => $"{clrTypeName}.Parse({textExpr})",
        _ => textExpr,
    };

    /// <summary>
    /// Emits [System.Xml.Serialization.XmlRoot(...)] on a class/enum that's unambiguously a root
    /// element's type, so `new XmlSerializer(typeof(X))` finds the right element name/namespace
    /// without a caller having to pass an XmlRootAttribute override by hand - see Refs.TryGetXmlRoot.
    /// GetSchema() still returns null (this tool doesn't generate XSD-derived schema info), so this
    /// attribute is what actually lets plain System.Xml.Serialization.XmlSerializer usage work.
    /// </summary>
    private static void EmitXmlRootAttributeIfAny(CodeWriter w, string clrName, Refs refs)
    {
        if (!refs.TryGetXmlRoot(clrName, out (string XmlName, string? XmlNamespace) root))
            return;

        w.Line(root.XmlNamespace is null
            ? $"[System.Xml.Serialization.XmlRoot({Lit(root.XmlName)})]"
            : $"[System.Xml.Serialization.XmlRoot(ElementName = {Lit(root.XmlName)}, Namespace = {Lit(root.XmlNamespace)})]");
    }

    private static string NsArg(string? ns) => ns is null ? "" : $", {Lit(ns)}";

    private static string Lit(string value)
    {
        StringBuilder sb = new(value.Length + 2);
        sb.Append('"');
        foreach (char ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private sealed class Refs
    {
        private readonly HashSet<string> _classNames = new(StringComparer.Ordinal);
        private readonly HashSet<string> _rowClassNames = new(StringComparer.Ordinal);
        private readonly HashSet<ClassTypeModel> _classesWithSubclasses = [];
        private readonly Dictionary<string, ClassTypeModel> _classesByName = new(StringComparer.Ordinal);
        private readonly Dictionary<string, (string XmlName, string? XmlNamespace)> _xmlRootByClrType = new(StringComparer.Ordinal);
        public Dictionary<string, EnumTypeModel> Enums { get; } = new(StringComparer.Ordinal);
        public Dictionary<string, UnionTypeModel> Unions { get; } = new(StringComparer.Ordinal);

        public Refs(SchemaModel model)
        {
            foreach (ClassTypeModel c in model.Classes)
            {
                _classNames.Add(c.ClrName);
                _classesByName[c.ClrName] = c;
                if (c.IsRow) _rowClassNames.Add(c.ClrName);
                if (c.BaseClass is { } baseClass) _classesWithSubclasses.Add(baseClass);
            }
            foreach (EnumTypeModel e in model.Enums) Enums[e.ClrName] = e;
            foreach (UnionTypeModel u in model.Unions) Unions[u.ClrName] = u;

            // A type only gets [XmlRoot] when exactly one (element name, namespace) is associated with
            // it across every root element - a type shared by two differently-named/namespaced root
            // elements has no single correct attribute value, so it's left unattributed; callers using
            // System.Xml.Serialization.XmlSerializer directly on that type need to pass an explicit
            // XmlRootAttribute override instead (same as any type used with more than one root name).
            HashSet<string> ambiguous = new(StringComparer.Ordinal);
            foreach (RootElementModel root in model.RootElements)
            {
                (string XmlName, string? XmlNamespace) key = (root.XmlName, root.XmlNamespace);
                if (_xmlRootByClrType.TryGetValue(root.ClrTypeName, out (string XmlName, string? XmlNamespace) existing))
                {
                    if (existing != key)
                        ambiguous.Add(root.ClrTypeName);
                }
                else
                {
                    _xmlRootByClrType[root.ClrTypeName] = key;
                }
            }
            foreach (string clrType in ambiguous)
                _xmlRootByClrType.Remove(clrType);
        }

        public bool IsClass(string clrTypeName) => _classNames.Contains(clrTypeName);

        public bool IsRowClass(string clrTypeName) => _rowClassNames.Contains(clrTypeName);

        public bool IsChoiceUnion(string clrTypeName) => Unions.TryGetValue(clrTypeName, out UnionTypeModel? u) && u.IsElementChoice;

        public bool HasSubclasses(ClassTypeModel c) => _classesWithSubclasses.Contains(c);

        /// <summary>
        /// Number of xsd:complexContent extension/restriction hops from clrTypeName up to its
        /// ultimate root class (0 for a root class or a type that isn't a known class at all, e.g. a
        /// union case's wrapper record, enum, or primitive - those never share an inheritance
        /// relationship with anything else here). Used to order a union's WriteXml `is`-pattern checks
        /// so a derived case's type never gets shadowed by an ancestor case that comes first.
        /// </summary>
        public int ClassInheritanceDepth(string clrTypeName)
        {
            int depth = 0;
            while (_classesByName.TryGetValue(clrTypeName, out ClassTypeModel? c) && c.BaseClass is { } baseClass)
            {
                depth++;
                clrTypeName = baseClass.ClrName;
            }
            return depth;
        }

        public bool TryGetXmlRoot(string clrTypeName, out (string XmlName, string? XmlNamespace) root) =>
            _xmlRootByClrType.TryGetValue(clrTypeName, out root);
    }
}
